services:
  - type: web
    name: hsvqnu-backend
    runtime: node
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
